### ISSUE TITLE
discrepancies in website and translation template

### ISSUE THREAD

**Issue by Spikarija** [ArkEcosystem/ARK.io-Translations#5]
I was reviewing the translation submitted today and came across several discrepancies between the template on Github and the actual website.

1. Team -> "ARK was founded by 27 individuals from around the globe. Currently ARK has 17 core team members, coming from 11 different countries, giving a decentralized team a whole new meaning." differs from the string provided by translation file, which is "ARK was founded by 27 individuals from around the globe. Currently ARK has 15 core team members, coming from 11 different countries, giving a decentralized team a whole new meaning."

2. Exchanges -> "Historical ARK Price and Volume" is absent in the provided translation file

3. Exchanges -> the table with headers "Date", "Price", "Volume", "Change" is absent from the provided translation file

4. Exchanges -> beneath the table mentioned above the string "* Price & chart conversion through BTC" is also absent from the translation file

5. Developers -> the first instance of ARK Github "Details" and "repositories" are missing translation strings even though there is one for "Details" in json translation file; "repositories" is absent in the provided translation file; note that the instances below (RPC...) display the correct translation string

6. Developers -> entries "ARK Desktop Wallet", "ARK Paper Wallet", "ARK Command Line Interface", and "ARK Lite Web Wallet" are missing from the provided translation file and it would make sense to translate them since they are translatable in the menu "Wallets"

7. Resources -> "Bounties" section contains "More Info" and "Send an email" strings, both of which are absent in the provided translation file

8. Media Kit -> "LOGOS" is absent in the provided translation file

**Comment by faustbrian** [comment]
1. Has been adjusted but not pushed to the repository yet.
2. Those are CryptoCompare Widgets so all text inside of them can't be modified as they are loaded via JavaScript.
3. Those are CryptoCompare Widgets so all text inside of them can't be modified as they are loaded via JavaScript.
4. Those are CryptoCompare Widgets so all text inside of them can't be modified as they are loaded via JavaScript.
5. Will be added.
6. Will be added.
7. Will be added.
8. https://github.com/ArkEcosystem/ARK.io-Translations/blob/master/si.json#L157

**Comment by faustbrian** [comment]
The missing lines have been added https://github.com/ArkEcosystem/ARK.io-Translations/blob/master/si.json#L286-L292
